import numpy as np
import gensim
from gensim.models import KeyedVectors
import nltk
from nltk.tokenize import word_tokenize
from sklearn.metrics.pairwise import cosine_similarity

nltk.download('punkt')
nltk.download('punkt_tab')

# Load pre-trained Word2Vec model (Google News word vectors)
# (Note: This requires downloading a large file: about 1.5GB)

model = KeyedVectors.load("word2vec-google-news-300.bin")

# Preset subject fields
fields = [
    "Entreprenuership",
    "Finance",
    "Investment Banking",
    "Private Equity",
    "Hedge Funds",
    "Venture Capital",
    "Corporate Finance",
    "Financial Planning",
    "Wealth Management",
    "Accounting",
    "Auditing",
    "Risk Management",
    "Taxation",
    "Consulting",
    "Management Consulting",
    "Strategy Consulting",
    "Operations Consulting",
    "IT Consulting",
    "Technology Consulting",
    "Healthcare Consulting",
    "Business Consulting",
    "Software Engineering",
    "Data Science",
    "Cybersecurity",
    "Artificial Intelligence",
    "Machine Learning",
    "Cloud Computing",
    "Product Management",
    "DevOps",
    "Network Security",
    "Information Technology",
    "System Administration",
    "Technical Support",
    "Data Engineering",
    "Web Development",
    "Mobile Development",
    "UX/UI Design",
    "Game Development",
    "Healthcare",
    "Nursing",
    "Public Health",
    "Healthcare Administration",
    "Clinical Research",
    "Pharmaceuticals",
    "Health Policy",
    "Medical Technology",
    "Telemedicine",
    "Health Data Analysis",
    "Environmental Science",
    "Education",
    "Teaching",
    "Higher Education",
    "K-12 Education",
    "Curriculum Development",
    "Educational Technology",
    "Academic Research",
    "School Administration",
    "Nonprofits",
    "Philanthropy",
    "Social Entrepreneurship",
    "Public Service",
    "Government",
    "Foreign Service",
    "Public Administration",
    "Urban Planning",
    "Policy Research",
    "Regulatory Affairs",
    "Law Enforcement",
    "Intelligence Analysis",
    "Defense",
    "Legal",
    "Corporate Law",
    "Intellectual Property Law",
    "Litigation",
    "Criminal Law",
    "Family Law",
    "Environmental Law",
    "Tax Law",
    "Real Estate Law",
    "Human Resources",
    "Talent Acquisition",
    "HR Management",
    "Organizational Development",
    "Employee Relations",
    "Compensation and Benefits",
    "Training and Development",
    "Sales",
    "Business Development",
    "Retail Management",
    "Customer Service",
    "E-commerce",
    "Marketing",
    "Brand Management",
    "Digital Marketing",
    "Content Marketing",
    "Market Research",
    "Advertising",
    "Public Relations",
    "Media",
    "Journalism",
    "Broadcasting",
    "Digital Media",
    "Film Production",
    "Music Industry",
    "Visual Arts",
    "Graphic Design",
    "Interior Design",
    "Fashion Design",
    "Architecture",
    "Civil Engineering",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Industrial Engineering",
    "Environmental Engineering",
    "Software Engineering",
    "Aerospace Engineering",
    "Robotics Engineering",
    "Marine Engineering",
    "Transportation Engineering",
    "Energy",
    "Renewable Energy",
    "Oil and Gas",
    "Mining",
    "Utilities Management",
    "Agriculture",
    "Food Science",
    "Veterinary Medicine",
    "Biotechnology",
    "Genetics",
    "Microbiology",
    "Clinical Trials",
    "Pharmacology",
    "Immunology",
    "Neuroscience",
    "Biochemistry",
    "Health Informatics",
    "Bioinformatics",
    "Molecular Biology",
    "Forensic Science",
    "Toxicology",
    "Nutrition",
    "Dietetics",
    "Sports Medicine",
    "Physical Therapy",
    "Occupational Therapy",
    "Speech Therapy",
    "Mental Health",
    "Counseling",
    "Psychology",
    "Social Work",
    "Family Therapy",
    "Addiction Counseling",
    "Community Health",
    "Health Education",
    "Environmental Health",
    "Occupational Health",
    "Sustainability",
    "Climate Change",
    "Ecology",
    "Wildlife Conservation",
    "Soil Science",
    "Fisheries Management",
    "Aquaculture",
    "Horticulture",
    "Agricultural Engineering",
    "Natural Resource Management",
    "Forestry",
    "Land Use Planning",
    "Disaster Management",
    "Logistics",
    "Supply Chain Management",
    "Operations Management",
    "Quality Control",
    "Project Management",
    "Business Process Improvement",
    "Change Management",
    "Lean Six Sigma",
    "Agile Methodologies",
    "Human Factors Engineering",
    "Information Systems",
    "Digital Transformation",
    "Big Data Analytics",
    "Business Analytics",
    "Predictive Modeling",
    "Data Visualization",
    "Geographic Information Systems (GIS)",
    "Real Estate Development",
    "Property Management",
    "Urban Development",
    "Event Planning",
    "Crisis Management",
    "Media Buying",
    "Content Creation",
    "Copywriting",
    "Public Speaking",
    "Market Strategy",
    "Sales Strategy",
    "Retail Strategy",
    "Executive Leadership",
    "Corporate Strategy",
    "Business Intelligence",
    "Financial Analysis",
    "Investment Management",
    "Compliance",
    "Risk Assessment",
    "Fraud Prevention",
    "Data Privacy",
    "Corporate Governance",
    "Digital Forensics",
    "Incident Response",
    "Threat Intelligence",
    "Security Auditing",
    "Penetration Testing",
    "Legal Compliance",
    "Real Estate Appraisal",
    "Tax Consulting",
    "Business Coaching",
    "Organizational Psychology",
    "Workplace Safety",
    "Diversity and Inclusion",
    "Workforce Development",
    "Talent Development",
    "Strategic Planning",
    "Investor Relations",
    "Economic Development",
    "International Relations",
    "Public Policy",
    "Healthcare Policy",
    "Economic Policy",
    "Environmental Policy",
    "Transport Policy",
    "Housing Policy",
    "Labor Policy",
    "Food Policy",
    "Technology Policy",
    "Energy Policy",
    "Community Development",
    "Public Engagement",
    "Political Science",
    "Sociology",
    "Anthropology",
    "History",
    "Philosophy",
    "Linguistics",
    "Religious Studies",
    "Cultural Studies",
    "Art History",
    "Theatre Arts",
    "Dance",
    "Music Performance",
    "Film Studies",
    "Creative Writing",
    "Journalism Ethics",
    "Documentary Filmmaking",
    "Stage Management",
    "Music Production",
    "Theater Production",
    "Event Coordination",
    "Community Arts",
    "Graphic Communications",
    "Photography",
    "Web Design",
    "Visual Communication",
    "Illustration",
    "Animation",
    "Interior Architecture",
    "Construction Management",
    "Facilities Management",
    "Landscaping",
    "Event Marketing",
    "Media Relations",
    "Health Marketing",
    "Advertising Sales",
    "Data Quality Management",
    "Data Warehousing",
    "Data Governance",
    "Corporate Communications",
    "Digital Communications",
    "Social Media Strategy",
    "Influencer Relations",
    "Fundraising",
    "Grant Writing",
    "Volunteer Coordination",
    "Program Evaluation",
    "Impact Assessment",
    "Research Administration",
    "Policy Analysis",
    "Statistical Analysis",
    "Econometrics",
    "Behavioral Economics",
    "Development Economics",
    "Urban Economics",
    "Health Economics",
    "International Development",
    "Humanitarian Aid",
    "Disaster Relief",
    "Crisis Response",
    "Emergency Management",
    "Security Management",
    "Intellectual Property Management",
    "Corporate Social Responsibility",
    "Environmental Sustainability",
    "Climate Policy",
    "Public Health Advocacy",
    "Cultural Heritage Management",
    "Art Curation",
    "Museum Studies",
    "Historical Preservation",
    "Tourism Management",
    "Travel and Leisure",
    "Sports Management",
    "Athletic Administration",
    "Exercise Science",
    "Kinesiology",
    "Health Coaching",
    "Personal Training",
    "Recreational Management",
    "Fitness Instruction",
    "Nutrition Counseling",
    "Wellness Program Management",
    "Health Communications",
    "Marketing Research",
    "Consumer Behavior",
    "Retail Marketing",
    "Strategic Marketing",
    "Email Marketing",
    "Web Analytics",
    "Content Strategy",
    "Audience Development",
    "Customer Experience Management",
    "User Experience Research",
    "User Research",
    "Information Architecture",
    "User Interface Design",
    "Human-Computer Interaction",
    "Information Technology Management",
    "IT Project Management",
    "Computer Networking",
    "Virtual Reality Development",
    "Augmented Reality Development",
    "Blockchain Technology",
    "FinTech",
    "HealthTech",
    "EdTech",
    "LegalTech",
    "Real Estate Tech",
    "CleanTech",
    "AgriTech",
    "BioTech",
    "Creative Technology",
    "Digital Innovation",
    "Internet of Things",
    "Smart Cities",
    "Big Data Strategy",
    "Quantitative Research",
    "Qualitative Research",
    "Survey Research",
    "Focus Group Facilitation",
    "Data Collection",
    "Statistical Software",
    "Market Trend Analysis",
    "Predictive Analytics",
    "Brand Strategy",
    "Digital Brand Management",
    "Event Marketing",
    "Corporate Sponsorship",
    "Lead Generation",
    "Sales Enablement",
    "Channel Management",
    "Sales Training",
    "Customer Retention",
    "Customer Loyalty",
    "Behavioral Psychology",
    "Crisis Counseling",
    "Digital Arts",
    "Applied Mathematics",
    "Statistics",
    "Bioengineering",
    "Agronomy",
    "Environmental Restoration"
]

# Preprocess text: tokenize and filter words that exist in the Word2Vec vocabulary
def preprocess_text(text):
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word in model]
    return tokens

# Get the vector for a list of tokens by averaging their embeddings
def get_average_vector(tokens):
    vectors = [model[word] for word in tokens if word in model]
    if not vectors:
        return np.zeros(300)  # Return zero vector if none of the words exist in the model
    return np.mean(vectors, axis=0)

# Calculate cosine similarity between two vectors
def cosine_similarity_vector(vec1, vec2):
    return cosine_similarity([vec1], [vec2])[0][0]

# Function to find the most similar field to the user input
def find_most_similar_fields(user_input, fields, top_n=3):
    # Preprocess user input
    user_tokens = preprocess_text(user_input)
    user_vector = get_average_vector(user_tokens)

    # Store similarities between user input and each field
    similarities = []
    
    for field in fields:
        field_tokens = preprocess_text(field)
        print(user_tokens + field_tokens)
        field_vector = get_average_vector(field_tokens)
        similarity = cosine_similarity_vector(user_vector, field_vector)
        similarities.append((field, similarity))
    
    # Sort the fields by similarity score in descending order
    similarities.sort(key=lambda x: x[1], reverse=True)
    
    # Return the top N matching fields
    return similarities[:top_n]

# Example user input
user_input = input("Enter user prompt:")

# Find top 3 matching fields
matching_fields = find_most_similar_fields(user_input, fields, top_n=3)

# Output results
print(user_input)
for field, similarity in matching_fields:
    print(f"Field: {field}, Similarity: {similarity:.4f}")